#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service

PROCESS_NAME="s3ql"


cat <<EOF

***************************************************************************************
*                                                                                     *
*                    END OF LIFE NOTICE AUGUST 17, 2025                               *
*                               tiredofit/s3ql                                        *
*                                                                                     *
* This image is no longer maintained as of and will not receive updates.              *
*                                                                                     *
* A successor image is available at:                                                  *
*                                                                                     *
* Repository | Documentation:                                                         *
*   - https://github.com/nfrastack/container-s3ql                                     *
*                                                                                     *
* Image Registries:                                                                   *
*   - https://hub.docker.com/r/nfrastack/s3ql                                         *
*   - https://github.com/nfrastack/container-s3ql/pkgs/container/container-s3ql       *
*                                                                                     *
* Please visit https://nfrastack.com for more information.                            *
*                                                                                     *
***************************************************************************************

EOF

sleep 15

bootstrap_filesystem
setup_s3ql

liftoff
